/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.gka.app

import org.example.gka.math.calc


fun main(args: Array<String>) {
    println(calc(args.firstOrNull() ?: error("Expects 1 argument")))
}
